services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:ajabado
    container_name: mariadb
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker_network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:ajabado
    container_name: wordpress
    env_file: .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - docker_network
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx:ajabado
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - docker_network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA_ROOT}/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA_ROOT}/wordpress

networks:
  docker_network:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
